# Generated by Django 4.2.4 on 2023-08-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_invocador', models.CharField(max_length=100)),
                ('nivel', models.IntegerField()),
                ('rol_principal', models.CharField(max_length=50)),
                ('campeon_principal', models.CharField(max_length=50)),
                ('rango', models.CharField(max_length=50)),
            ],
        ),
    ]
